### ISSUE TITLE
Write good descriptions of what the from_many* methods do

### ISSUE THREAD

**Issue by stringertheory** [datascopeanalytics/traces#1]
Right, now, they're pretty impenetrable.

**Comment by vlsd** [comment]
I can figure out what `sum` does, but you're right, `union` and `set` and mysterious. Maybe we can try having a conversation here and then using that as a basis for documentation.

**Comment by deanmalmgren** [comment]
FWIW I'd recommend throwing together a pull request and using that as a
medium to comment on the changes and revise things accordingly. It avoids
having to agree and makes it easy to accept the recommendations. Just a
thought from some dude sitting on a Metra train...

On Wed, Jan 13, 2016 at 3:54 PM Vlad <notifications@github.com> wrote:

> I can figure out what sum does, but you're right, union and set and
> mysterious. Maybe we can try having a conversation here and then using that
> as a basis for documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datascopeanalytics/traces/issues/1#issuecomment-171449114>
> .
>
-- 
*dean malmgren | +1.312.884.9214 *
*partner, data scientist | datascope*
