### ISSUE TITLE
Values in TimeSeries.distribution() are sentence-cased regardless of how vales were added to the TimeSeries 

### ISSUE THREAD

**Issue by michaelmoliterno** [datascopeanalytics/traces#15]
If you are using strings as values in a TimeSeries:
```
ts = traces.TimeSeries()
ts[1] = JUNK
ts[3] = JANK
ts[5] = WHAT
```

If you call something like `ts.distrubution(min, max)`, you would see something like this:

```
Histogram(None, 1000, {'Jank': 0.16008504570112725, 'Junk': 0.04229136076598496, 'What': 0.797577092766277})
```

It looks like somewhere along the line, the string-values are getting sentence-cased. Not sure exactly where yet, but this could be confusing or cause silly bugs if looking-up these objects with the wrong value.

**Comment by stringertheory** [comment]
What is the value of JANK? Is it not "Jank"?

**Comment by michaelmoliterno** [comment]
Hmmm. I was not clear above. 

If you initiate a ts like this... with the values as literal strings. 
```
ts[1] = "JUNK"
ts[3] = "JANK"
```

When you run ts.distrubution(), the values are sentence-cased: "Jank", "Junk", ...

**Comment by stringertheory** [comment]
I can't reproduce... here's my results.

```
import traces

ts = traces.TimeSeries()
ts[1] = 'JUNK'
ts[3] = 'JANK'
ts[5] = 'WHAT'

print ts.distribution(0, 6)
Histogram(None, 1000, {'JANK': 0.3333333333333333, 'JUNK': 0.5, 'WHAT': 0.16666666666666666})
```

I'd be stymied if this is happening in traces, since a `grep title -R traces/` shows there isn't anything in the code that could be title-casing. Could you show an example?

**Comment by stringertheory** [comment]
was a caching thing http://martinfowler.com/bliki/TwoHardThings.html
