### ISSUE TITLE
[Question] How to recreate traces chart?

### ISSUE THREAD

**Issue by manugarri** [datascopeanalytics/traces#150]
I wonder, how could one plot traces'  Signature plot? ![signature plot](https://traces.readthedocs.io/en/latest/_static/img/logo.png) ? 

I was wondering if the library has anything to do with the charts (as per the docs that is not the case) but seeing a couple of charts like that in the docs made me think that maybe producing that kind of charts is within the scope of the projects.

**Comment by stringertheory** [comment]
Good question! We intentionally want to keep charts out of traces, in the spirit of attempting to [do one thing well](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well). That particular image was made with traces and [xmgrace](http://plasma-gate.weizmann.ac.il/Grace/).

**Comment by manugarri** [comment]
oooh snap!
