### ISSUE TITLE
When using a mask with TimeSeries.distribution(), mask.start() is called in `timeseries.py` but `start()` doesn't exist

### ISSUE THREAD

**Issue by michaelmoliterno** [datascopeanalytics/traces#16]
I think this will be fixed with the next bump; looked for an issue related to this but didn't find one.  Feel free to close this out if it was as simple as defining `start()` for `TimeSeries`.

```
Traceback (most recent call last):
  File "run_plots.py", line 25, in <module>
    make_plots()
  File "/Users/mjfm/projects/modustri/analysis/plots/see_cart_trips.py", line 55, in make_plots
    mask = front_ts,
  File "/Users/mjfm/Virtualenvs/modustri/lib/python2.7/site-packages/traces/timeseries.py", line 622, in distribution
    new_ts = self.slice(mask.start(), mask.end())
AttributeError: 'TimeSeries' object has no attribute 'start'
```

**Comment by stringertheory** [comment]
Ah, this is a good one — the problem is that mask needs to be an instance of `Domain`.

**Comment by stringertheory** [comment]
until now, now a mask should work... we should probably add a test case to make sure it keeps working — creating separate issue.
