### ISSUE TITLE
SorterContainers >2.0 breaks backwards compatibility

### ISSUE THREAD

**Issue by vlsd** [datascopeanalytics/traces#221]
This is a reminder that traces doesn't currently work with the current version of SortedContainers because of a backwards incompatibility when iterating over a SortedDict. I should look into this and remedy it.

**Comment by stringertheory** [comment]
fixed with https://github.com/datascopeanalytics/traces/commit/b7354cdf44d0bce3755713a24cd9b9f9ba72ca33
