### ISSUE TITLE
Feature Request: linear interpolation for mean

### ISSUE THREAD

**Issue by Inspirateur** [datascopeanalytics/traces#225]
So I recently discovered this nice library and decided to try it since I got unevenly spaced data,
however I found out today that the .mean() wasn't doing linear interpolation as I thought it would be:
```python
>>> from traces import TimeSeries
>>> t = TimeSeries()
>>> t[0] = 0
>>> t[1] = 0
>>> t[3] = 20
>>> t.mean(0, 2)
0.0
```
With linear interpolation between 2 points we would find that t[2] = 10 and doing the average from 0 to 2 would give us 3.333 in this example.
A simple optional argument in mean() to choose the interpolation method would be fantastic, and I really think that it would be useful to many users who are not using traces exclusively for binary data (where linear interpolation would make no sense).
I know that we can re-sample the TimeSeries but I think a shortcut like this would be really neat since this library is designed with ease of use in mind.

Thanks for reading and have a nice day 👋

**Comment by stringertheory** [comment]
@Inspirateur thanks for the suggestion! I agree this would be useful. To double check I'm understanding, in the example you gave the mean between 0 and 2 should be 2.5, right? (and 3.333 if taken between 0 and 3?)

![image](https://user-images.githubusercontent.com/1110950/71550017-cbd33c00-298c-11ea-9c66-525657a2aa84.png)

**Comment by stringertheory** [comment]
added this in 05a14608d06b06dfc589ae9c247d300b89f956b5
