### ISSUE TITLE
add possibility to write ts[start:end] = v to change value on an interval

### ISSUE THREAD

**Issue by sdementen** [datascopeanalytics/traces#40]
I have a use case where I need to change the value of a timeseries on an interval without changing the value outside of the interval, ie do something like ts[start:end] = value.
Just setting 

``` python
ts[end] = ts[end]   # freezing/anchoring the current value of ts as of [end, ...)
ts[start] = value      # changing the value as of [start, ...)
```

may fail as intermediate points in [start,end) may exist ==> we need to remove all intermediate points (which is easy as `ts.iterperiods(start,end)` provides them nicely).

I think the function below does it properly (but it would be better integrated in the **item** to use the slice notation)

``` python
def set_slice(ts, start, end, value):
    """
   ts[start:end] = value ==> call set_slice(ts, start, end, value)
    Set the value of the ts so that
    - on the interval [start, end) we have the new value
    - on [end, ...) we haven't change the value
    - on (..., start) we haven't change the value neither
    We replace the value of the ts on an interval.

    :param ts: 
    :param start: 
    :param end: 
    :param value: 
    :return: 
    """
    # for each interval to render
    for i, (s, e, v) in enumerate(list(ts.iterperiods(start, end))):
        # look at all intervals included in the current interval
        # (always at least 1)
        if i == 0:
            # if the first, set initial value to new value of range
            ts[s] = value
        else:
            # otherwise, remove intermediate key
            del ts[s]
    # finish by setting the end of the interval to the previous value
    ts[end] = v


```

**Comment by stringertheory** [comment]
Good idea! I can see how that could be useful in some cases. I'd welcome a pull request (especially if you write a couple of accompanying tests) — I can also add something like this in, though it might not be for a week or two.

I think it might be good to include a `compact=False` keyword argument, too, to keep consistent with `set` and to specify whether the endpoints of the interval will always be included as measurements.

**Comment by sdementen** [comment]
I made PR #41

**Comment by sdementen** [comment]
I have cleaned the PR to fix pep8 issues. Any chance for merge any time soon ?

**Comment by stringertheory** [comment]
Thanks @sdementen! I'll merge it in sometime this week when I get a chance
