### ISSUE TITLE
Add functionality/documentation for changing the "default" value before first entry

### ISSUE THREAD

**Issue by vlsd** [datascopeanalytics/traces#5]
Right now, the default value starts at zero. Several simple examples where this might not need be the case:
- a sensor where the readings are between 0 and 16, centered at 8
- a sensor where 1 is neutral and 0 is activated
- a signal representing the inverse or complement of another signal
- etc.

**Comment by stringertheory** [comment]
Going through and doing some issue cleaning. Closing this one since there is the `default_value` argument.
