### ISSUE TITLE
Add `compact` option to `iterperiods()`

### ISSUE THREAD

**Issue by vlsd** [datascopeanalytics/traces#8]
This would merge adjacent periods that have the same value and return them as only one period. Ideally this would be done efficiently, although I'm unclear what that means (store a `compact` version of the timeseries along with the non-compact one?)

**Comment by stringertheory** [comment]
What is the use case for this?

I'd like to avoid adding complexity to the interface except if it's a common use case. Here's an example of how you could accomplish this efficiently:

```python
import traces

class VladSeries(traces.TimeSeries):

    def iterperiods(self):

        duration = 0
        t, previous_value = self.get_by_index(0)
        for t_i, duration_i, value_i in super(VladSeries, self).iterperiods():
            if value_i == previous_value:
                duration += duration_i
            else:
                yield t, duration, previous_value
                duration = duration_i
                t, previous_value = t_i, value_i

        if value_i == previous_value:
            yield t, duration, previous_value
```

**Comment by stringertheory** [comment]
If I understand when you might want this from our lunchtime conversation, it's when a TimeSeries is created from summing up several TimeSeries: the result has many "unnecessary" repeated values (that is, in your case you don't care about when the measurements were taken).

One way of addressing what you are trying to use this for would be to add a `TimeSeries.compact` method that would get rid of any consecutive measurements with the same value. Then, you could compact the summed time series, and the repeated values would be gone. Then, calling `iterperiods` won't have any unnecessary repeated values.

I could imagine this being useful for optimization: if you need to transfer the values of a TimeSeries over a network or something where having the extra information just makes it take longer, or if you are doing a bunch of extra manipulation of the TimeSeries and want to make it run faster.
