### ISSUE TITLE
Trying to calculate the mean of an empty Histogram fails

### ISSUE THREAD

**Issue by vlsd** [datascopeanalytics/traces#98]
Running `.mean()` on an empty Histogram object (`Histogram(None, 1000, {0: 0.0})`) fails with a divide by zero error:

```
  File "/src/traces/traces/histogram.py", line 30, in mean
    return weighted_sum / float(self.total())
ZeroDivisionError: float division by zero
```

**Comment by vlsd** [comment]
To be clear, in order to create that Histogram object one needs to do so explicitly, or by manually adding/subtracting two Histogram objects.

**Comment by stringertheory** [comment]
I tend to think this _should_ fail, but agree it could fail with a more informative error message — is that what you have in mind?

**Comment by vlsd** [comment]
I expect the behavior of a `{0:0}` Histogram to be identical to that of an empty Histogram. I believe right now only one of them fails. I think they should either both fail (and raise the same exception) or both return the same thing.

**Comment by stringertheory** [comment]
I get `ZeroDivisionError: float division by zero` for both `traces.Histogram.from_dict({0:0}).mean()` and `traces.Histogram().mean()`.

**Comment by vlsd** [comment]
I was remembering wrong then. Sorry.

I still feel that raising an exception here is a bit heavy handed, since it basically means that some of the methods on the class fail to run for very vanilla objects. Idea: we could return `None` when the Histogram is empty?

**Comment by stringertheory** [comment]
This has been resolved, so closing issue.
